[package]
name = "sswa"
version = "0.1.0"
edition = "2021"

[dependencies]
ssup = { path = "../ssup" }

clap = { version = "3.0.14", features = ["derive"] }
anni-clap-handler = { git = "https://github.com/ProjectAnni/anni", features = ["async"] }
directories-next = "2.0.0"

tokio = { version = "1", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }
toml = "0.5.8"
anyhow = "1"
