# 模板的默认投稿帐号
default-user = "me"

# 标题
title = "【字幕】【偶像大师百万广播{{num}}回】{{title}}【MillionRADIO】"
# 描述
description = '''片源：RabbitC
翻译：{{translators}}
校对：{{jiaodui}}
时间轴：{{subtitle}}'''
# 转载来源，该字段存在且不为空时以转载形式投稿，否则投成自制
forward-source = "765.million"
# 投稿分区
tid = 152
# 封面图片路径
# 当留空或值为 auto 时，自动从第一个视频（不包含前缀视频）中随机提取
cover = "./cover.png"
# 动态文本
dynamic-text = ""
# 标签
tags = ["田所梓", "山崎遥", "麻仓桃", "偶像大师百万广播", "{guests}"]
# 定时投稿
display-time = "tomorrow 10:00"
# 字幕（TODO）
subtitle = { open = false, lang = "zh-cn" }
# 前缀视频，在投稿时自动添加在选中视频**前面**
video-prefix = [
    # 建议写绝对路径，相对路径是相对命令执行时候的 CWD
    "/tmp/prefix.mp4",
]
# 后缀视频，在投稿时自动添加在选中视频**后面**
video-suffix = []

# 变量对应的解释文本，在需要用户手动输入时作为提示文本展示
[variables]
num = "广播回数"
title = "标题"
translators = "翻译"
jiaodui = "校对"
subtitle = "时间轴"
guests = "嘉宾 Tag"

# 变量的默认值，在需要用户手动输入时作为默认文本
[defaults]
num = "123"
title = "默认标题"